server:
  port: 8486

spring:
  uploadPath: D:\upload\
  servlet:
    multipart:
      #单个数据的大小
      max-file-size: 100MB
      #总数据的大小
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 0
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/title_evaluation?characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


web:
  # Swagger相关配置
  swagger:
    basePackage: com.evildoer.evaluation
    title: EVALUATION API
    description: EVALUATION VUE API Document.
    version: 1.0
    author: evildoer
    url: https://baidu.com
    email: 123456@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto

